sudo: required
language: generic 

services: 
  - docker

before_install:
  - docker build -t delawarecxin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true delawarecxin/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-1-306476662672"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"